spring.application.name=jobtracker
spring.datasource.url=jdbc:mysql://localhost:3306/jobtracker?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=CHANGE_THIS_A_LONG_RANDOM_KEY_AT_LEAST_32_CHARS
jwt.expiration-ms=86400000

razorpay.key-id=YOUR_TEST_KEY_ID
razorpay.key-secret=YOUR_TEST_KEY_SECRET
razorpay.webhook-secret=YOUR_WEBHOOK_SECRET

logging.level.org.springframework.security=TRACE