CREATE TABLE companies (
    id       VARCHAR(36)  NOT NULL,
    name     VARCHAR(100) NOT NULL,
    category VARCHAR(50)  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_company_name UNIQUE (name)
) ENGINE=InnoDB;

INSERT INTO companies (id, name, category) VALUES
(UUID(), 'TCS', 'IT Services'),
(UUID(), 'Infosys', 'IT Services'),
(UUID(), 'Wipro', 'IT Services'),
(UUID(), 'HCLTech', 'IT Services'),
(UUID(), 'Tech Mahindra', 'IT Services'),
(UUID(), 'LTIMindtree', 'IT Services'),
(UUID(), 'Cognizant', 'IT Services'),
(UUID(), 'Capgemini', 'IT Services'),
(UUID(), 'Accenture', 'IT Services'),
(UUID(), 'IBM', 'IT Services'),
(UUID(), 'Genpact', 'IT Services'),
(UUID(), 'Deloitte', 'Consulting'),
(UUID(), 'EY', 'Consulting'),
(UUID(), 'KPMG', 'Consulting'),
(UUID(), 'PwC', 'Consulting'),
(UUID(), 'Microsoft', 'Product'),
(UUID(), 'Google', 'Product'),
(UUID(), 'Amazon', 'Product'),
(UUID(), 'Adobe', 'Product'),
(UUID(), 'Oracle', 'Product'),
(UUID(), 'SAP', 'Product'),
(UUID(), 'Salesforce', 'Product'),
(UUID(), 'Cisco', 'Product'),
(UUID(), 'Intel', 'Product'),
(UUID(), 'Flipkart', 'Startup'),
(UUID(), 'Zomato', 'Startup'),
(UUID(), 'Swiggy', 'Startup'),
(UUID(), 'Paytm', 'Startup'),
(UUID(), 'PhonePe', 'Startup'),
(UUID(), 'Razorpay', 'Startup');